### ISSUE TITLE
🐛 [BUG] Disney API: Network Error

### ISSUE THREAD

**Issue by EKalDTE** [ManuCastrillonM/disney-api#32]
# 🐛 Bug report

## 📝 Description

One of the projects in my Kotlin Coroutines tutorial is using the Disney API and I came across a network error on the API endpoint when the sample Android application was trying to send a GET request to the https://api.disneyapi.dev/character end point. 

I could able to log the following error I get upon request:

**503 Service Unavailable http://api.disneyapi.dev/character**

A network error is displayed on the homepage of Disney API as well. 

## 📌 Steps to reproduce

1. Go to [Disney API website](https://disneyapi.dev/)
2. Click on the **Send** button to send a GET request to the following endpoint: https://api.disneyapi.dev/character
3. See the error on the **Try It** section as it states: "Error: Network Error"

## 👀 Screenshots

![Screen Shot 2023-10-21 at 9 30 53 PM](https://github.com/ManuCastrillonM/disney-api/assets/139500282/65871209-16d6-41b8-9238-38877ed04156)

**Desktop (please complete the following information):**

- OS: MacOS - Monterey Version 12.5
- Browser: Chrome
- Version: Version 118.0.5993.88 

**Smartphone (please complete the following information):**

- Device: Pixel 6 Emulator
- OS: Android API 30

**Comment by Aquilesxd100** [comment]
Soo sad, that was one of my main used APIs to generate characters in my browser game, the api is down for months :c
https://www.linkedin.com/posts/fernando-alan-fillmann-0188b024a_react-api-apirest-activity-7081375992392429568-ldCA?utm_source=share&utm_medium=member_desktop

**Comment by ManuCastrillonM** [comment]
Hello!
This project is completely free and I work on it in my free time. However, the infrastructure required to keep it running has a monthly cost which I have been covering for the past three years. In order to keep the API available, I enabled a "[support](https://disneyapi.dev/support-us/)" option on the website where you can contribute to help cover the monthly expenses.

The cost is not very high, but it adds up over time, and the availability of the service will depend on the support we receive. I appreciate your use of the API and hope that you can contribute to keeping it available.
